ToniAuto2003/Controllers/CarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;
using System.Runtime.CompilerServices;
using ToniAuto2003.Attributes;
using ToniAuto2003.Core.Contracts;
using ToniAuto2003.Core.Extensions;
using ToniAuto2003.Core.Models.Car;
using ToniAuto2003.Extensions;
using ToniAuto2003.Infrastructure.Data;

namespace ToniAuto2003.Controllers
{
    public class CarController : BaseController
    {

        private readonly ICarService carService;
        private readonly IAgentService agentService;
        private readonly IClientService clientService;

        public CarController(ICarService _carService, IAgentService _agentService, IClientService _clientservice)
        {
            carService = _carService;
            agentService = _agentService;
            clientService = _clientservice;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery]AllCarsQueryModel query)
        {   
            var model =await carService.AllAsync(
                query.Category,
                query.SearchTerm,
                query.Sorting,
                query.currentPage,
                query.CarsPerpage);

            query.TotalCarsCount = model.totalCarsCount;
            query.Cars = model.Cars;
            query.Categories=await carService.AllCategoriesNamesAsync();
            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> Mine()
        {
            var userId = User.Id();
            IEnumerable<CarServiceModel> model;

            if (await agentService.ExistByIdAsync(userId)||User.IsAdmin())
            {
                int agentId = await agentService.GetAgentIdAsync(userId) ?? 0;

                model = await carService.AllCarsByAgentIdAsync(agentId);
            }
            else
            {
                if (await clientService.ExistByIdAsync(userId))
                {
                    model = await carService.AllCarsByUserIdAsync(userId);
                }
                else
                {
                    return RedirectToAction("Index","Home");
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id,string information)
        {
            if (await carService.ExistsAsync(id)==false)
            {
                return BadRequest();
            }

            var model = await carService.CarDetailsByIdAsync(id);

            if (information!=model.GetInformation())
            {
                return BadRequest();
            }
            return View(model);
        }

        [HttpGet]
        [MustBeAnAgentAtribute]
        public async Task<IActionResult> Add()
        {
            var model = new CarFormModel()
            {
                Categories = await carService.AllCategoriesAsync(),
                Leasings = await carService.AllLeasingsAsync()
            };
            return View(model);
        }
        [MustBeAnAgentAtribute]
        [HttpPost]
        public async Task<IActionResult> Add(CarFormModel car)
        {
            if (await carService.CategoryExistsAsync(car.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(car.CategoryId), "Category does not exist");
            }

            if (await carService.LeasingExistsAsync(car.LeasingId) == false)
            {
                ModelState.AddModelError(nameof(car.LeasingId), "");
            }

            if (ModelState.IsValid == false)
            {
                car.Categories = await carService.AllCategoriesAsync();
                car.Leasings = await carService.AllLeasingsAsync();

                return View(car);
            }

            int? agentId = await agentService.GetAgentIdAsync(User.Id());

            int newCarId = await carService.CreateAsync(car, agentId ?? 0);

            return RedirectToAction(nameof(Details), new { id = newCarId, information=car.GetInformation()});
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await carService.ExistsAsync(id)==false)
            {
                return BadRequest();
            }

            if (await carService.HasAgentWithIdAsync(id,User.Id())== false
                && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var model=await carService.GetCarFormModelByIdasync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CarFormModel car)
        {
            if (await carService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasAgentWithIdAsync(id, User.Id()) == false
                && User.IsAdmin()==false)
            {
                return Unauthorized();
            }

            if (await carService.CategoryExistsAsync(car.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(car.CategoryId), "Category does not exist");
            }

            if (ModelState.IsValid==false)
            {
               car.Categories=await carService.AllCategoriesAsync();
                car.Leasings = await carService.AllLeasingsAsync();

                return View(car);
            }

            await carService.EditAsync(id, car);
            return RedirectToAction(nameof(Details), new { id = id, information = car.GetInformation() });
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (await carService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasAgentWithIdAsync(id,User.Id())==false
                 && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var car=await carService.CarDetailsByIdAsync(id);
            var model = new CarDetailsViewModel()
            {
                Id= id,
                Year=car.Year,
                Model=car.Model,
                Make=car.Make,
                ImageUrl=car.ImageUrl
                
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CarDetailsViewModel model)
        {
            if (await carService.ExistsAsync(model.Id) == false)
            {
                return BadRequest();
            }

            if (await carService.HasAgentWithIdAsync(model.Id, User.Id())==false
                 && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            await carService.DeleteAsync(model.Id);

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> Buy(int id)
        {
            if (await carService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await agentService.ExistByIdAsync(User.Id())
                 && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            if (await carService.IsBuyedAsync(id))
            {
                return BadRequest();
            }

            var client = await clientService.GetClientFormModelById(User.Id());
            var car = carService.GetCarFormModelByIdasync(id);
            if (User.IsAdmin())
            {
                await carService.BuyAsync(id, User.Id());
                return RedirectToAction(nameof(All));
            }
            else
            {
                if (client.Money >= ((double)car.Result.Price))
                {
                    await carService.BuyAsync(id, User.Id());
                    await clientService.BuyAsync(client.Id, ((double)car.Result.Price));

                    return RedirectToAction(nameof(All));
                }
                else
                {
                    return BadRequest();
                }
            }
        }
        [HttpPost]
        public async Task<IActionResult> Sell(int id)
        {
            if (await carService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await carService.IsBuyedByUserWithIdAsync(id,User.Id()) == false)
            {
                return Unauthorized();
            }
            var client = await clientService.GetClientFormModelById(User.Id());
            var car = carService.GetCarFormModelByIdasync(id);
            await carService.SellAsync(id);
            await clientService.SellAsync(client.Id, ((double)car.Result.Price));

            return RedirectToAction(nameof(All));
        }
    }
}

ToniAuto2003/Controllers/LeasingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using ToniAuto2003.Attributes;
using ToniAuto2003.Core.Contracts;
using ToniAuto2003.Core.Models.Car;
using ToniAuto2003.Core.Models.Leasing;
using ToniAuto2003.Core.Services;
using ToniAuto2003.Extensions;
using ToniAuto2003.Infrastructure.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace ToniAuto2003.Controllers
{
    [Authorize]
    public class LeasingController : Controller
    {
        private readonly ILeasingService leasingService;
        private readonly IAgentService agentService;

        public LeasingController(ILeasingService _leasingservice, IAgentService _agentService)
        {
            leasingService = _leasingservice;
            agentService = _agentService;
        }
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery]AllLeasingQueryModel query)
        {
            var model = await leasingService.AllAsync(
                query.SearchTerm,
                query.Sorting,
                query.currentPage,
                query.LeasingsPerpage);

            query.TotalLeasingsCount = model.TotalLeasingsCount;
            query.Leasings = model.Leasings;
            return View(query);
        }

        [HttpGet]
        [MustBeAnAgentAtribute]
        public async Task<IActionResult> Add()
        {
            var model = new LeasingFormModel()
            {
            };
            return View(model);
        }
        [MustBeAnAgentAtribute]
        [HttpPost]
        public async Task<IActionResult> Add(LeasingFormModel car)
        {

            if (ModelState.IsValid == false)
            {
                return View(car);
            }

            int? agentId = await agentService.GetAgentIdAsync(User.Id());

            int newLeasingId = await leasingService.CreateAsync(car, agentId ?? 0);

            return RedirectToAction(nameof(Details), new { id = newLeasingId });
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (await leasingService.ExistsAsync(id)==false)
            {
                return BadRequest();
            }
            else
            {
                var model=await leasingService.LeasingDetailsByIdAsync(id);

                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await leasingService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await leasingService.HasAgentWithIdAsync(id, User.Id()) == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var model = await leasingService.GetLeasingFormModelByIdAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, LeasingServiceModel leasing)
        {
            if (await leasingService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await leasingService.HasAgentWithIdAsync(id, User.Id()) == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            if (ModelState.IsValid == false)
            {
                return View(leasing);
            }

            await leasingService.EditAsync(id, leasing);
            return RedirectToAction(nameof(Details), new { id = id });
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (await leasingService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await leasingService.HasAgentWithIdAsync(id, User.Id()) == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var leasing = await leasingService.LeasingDetailsByIdAsync(id);
            var model = new LeasingDetailsViewModel()
            {
                Id = id,
                Name=leasing.Name,
                AmountPerMonth=leasing.AmountPerMonth,
                Months=leasing.Months
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(LeasingDetailsViewModel model)
        {
            if (await leasingService.ExistsAsync(model.Id) == false)
            {
                return BadRequest();
            }

            if (await leasingService.HasAgentWithIdAsync(model.Id, User.Id()) == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            await leasingService.DeleteAsync(model.Id);

            return RedirectToAction(nameof(All));
        }
    }
}

ToniAuto2003/Views/Shared/_CarFormPartialView.cshtml
@model CarFormModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Year"></label>
                <input asp-for="Year" class="form-control" placeholder="Year...">
                <span asp-validation-for="Year" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Make"></label>
                <input asp-for="Make" class="form-control" placeholder="Make...">
                <span asp-validation-for="Make" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model"></label>
                <textarea asp-for="Model" rows="1" class="form-control" placeholder="Model..."></textarea>
                <span asp-validation-for="Model" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Your fine URL here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LeasingId">Leasing</label>
                <select asp-for="LeasingId" class="form-control">
                    @foreach (var leasing in Model.Leasings)
                    {
                        <option value="@leasing.Id">@leasing.Name</option>
                    }
                </select>
                <span asp-validation-for="LeasingId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

ToniAuto2003/Views/Shared/_CarPartial.cshtml
@model CarServiceModel
@inject IAgentService agentService
@inject ICarService carService

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="House Image">
        <div class="card-body text-center">
            <h4>@Model.Year</h4>
            <h6>Make: <b>@Model.Make</b></h6>
            <h6>Model: <b>@Model.Model</b></h6>
            <h6>
                Price Per Month:
                <b>@String.Format("{0:f2}", Model.Price) BGN</b>
            </h6>
            <h6>(@(Model.IsBuyed ? "Buyed" : "Available"))</h6>
            <br />
            <a asp-controller="Car" asp-action="Details" asp-route-id="@Model.Id" asp-route-information="@Model.GetInformation()"
               class="btn btn-success">Details</a>
            @if (this.User.Identity.IsAuthenticated)
            {
                if (await carService.HasAgentWithIdAsync(Model.Id,User.Id())
                ||User.IsAdmin())
                {
                    <a asp-controller="Car" asp-action="Edit" asp-route-id="@Model.Id"
               class="btn btn-warning">Edit</a>
                <a asp-controller="Car" asp-action="Delete" asp-route-id="@Model.Id"
               class="btn btn-danger">Delete</a>
                }
                <p></p>
                @if (!Model.IsBuyed && (await agentService.ExistByIdAsync(User.Id())) == false || User.IsAdmin())
                {
                    <form class="input-group-sm" asp-controller="Car"
                  asp-action="Buy" asp-route-id="@Model.Id" method="post">
                        <input class="btn btn-primary" type="submit" value="Buy" />
                    </form>
                }
                else if(await carService.IsBuyedByUserWithIdAsync(Model.Id,User.Id()))
                {
                    <form asp-controller="Car" asp-action="Sell"
                  asp-route-id="@Model.Id" method="post">
                        <input class="btn btn-primary" type="submit" value="Sell" />
                    </form>
                }
            }
        </div>
    </div>
</div>

ToniAuto2003/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToniAuto2003</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToniAuto2003.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Best Dealership World Wide</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @await Component.InvokeAsync(nameof(MainMenuComponent))
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - ToniAuto2003
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToniAuto2003/Views/Shared/_LeasingFormPartialView.cshtml
@model LeasingServiceModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Name...">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmountPerMonth"></label>
                <input asp-for="AmountPerMonth" class="form-control" placeholder="AmountPerMonth...">
                <span asp-validation-for="AmountPerMonth" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Months"></label>
                <textarea asp-for="Months" rows="1" class="form-control" placeholder="Model..."></textarea>
                <span asp-validation-for="Months" class="small text-danger"></span>
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

ToniAuto2003/Views/Shared/_LeasingsPartial.cshtml
@model LeasingServiceModel
@inject IAgentService agentService
@inject ILeasingService leasingService

<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h6>AmountPerMonth: <b>@Model.AmountPerMonth</b></h6>
            <h6>Months: <b>@Model.Months</b></h6>
            <a asp-controller="Leasing" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Details</a>
            @if (this.User.Identity.IsAuthenticated && await agentService.ExistByIdAsync(User.Id()) || User.IsAdmin())
            {
                @if (await leasingService.HasAgentWithIdAsync(Model.Id, User.Id()) || User.IsAdmin())
                {
                    <a asp-controller="Leasing" asp-action="Edit" asp-route-id="@Model.Id"
               class="btn btn-warning">Edit</a>
                <a asp-controller="Leasing" asp-action="Delete" asp-route-id="@Model.Id"
               class="btn btn-danger">Delete</a>
                }
                <p></p>
            }
        </div>
    </div>
</div>